//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Bk_id { get; set; }
        public string Bk_Movie_id { get; set; }
        public int Bk_SubTh_id { get; set; }
        public int BK_STDI_id { get; set; }
        public string BK_User { get; set; }
        public System.DateTime BK_Time { get; set; }
        public int BK_Seat { get; set; }
    
        public virtual MovieDetail MovieDetail { get; set; }
        public virtual ShowTimingsDetailsInfo ShowTimingsDetailsInfo { get; set; }
        public virtual SubTheatre SubTheatre { get; set; }
        public virtual BookingSeatInfo BookingSeatInfo { get; set; }
    }
}
