//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectMovieFinalEntities : DbContext
    {
        public ProjectMovieFinalEntities()
            : base("name=ProjectMovieFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<BookingSeatInfo> BookingSeatInfoes { get; set; }
        public DbSet<MovieDetail> MovieDetails { get; set; }
        public DbSet<MovieTheatre> MovieTheatres { get; set; }
        public DbSet<SeatGenerator> SeatGenerators { get; set; }
        public DbSet<ShowTimingsDetailsInfo> ShowTimingsDetailsInfoes { get; set; }
        public DbSet<SubTheatre> SubTheatres { get; set; }
        public DbSet<TheatreCompany> TheatreCompanies { get; set; }
    }
}
