//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTheatre
    {
        public int MoTh_id { get; set; }
        public string Mov_id { get; set; }
        public int SubTh_id { get; set; }
        public int ShowTimingsDetailsInfo_STDI_id { get; set; }
        public Nullable<System.DateTime> ShowUntill { get; set; }
    
        public virtual MovieDetail MovieDetail { get; set; }
        public virtual ShowTimingsDetailsInfo ShowTimingsDetailsInfo { get; set; }
        public virtual SubTheatre SubTheatre { get; set; }
    }
}
