//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDetail
    {
        public MovieDetail()
        {
            this.Bookings = new HashSet<Booking>();
            this.MovieTheatres = new HashSet<MovieTheatre>();
        }
    
        public string mov_id { get; set; }
        public string mov_title { get; set; }
        public string mov_genre { get; set; }
        public string mov_duration { get; set; }
        public string mov_rating { get; set; }
        public System.DateTime mov_releasedate { get; set; }
        public string mov_visiotype { get; set; }
        public string mov_language { get; set; }
        public string mov_maincast { get; set; }
        public string mov_director { get; set; }
        public string mov_subtitle { get; set; }
        public string mov_price { get; set; }
        public string mov_url { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<MovieTheatre> MovieTheatres { get; set; }
    }
}
