//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatGenerator
    {
        public int Seat_id { get; set; }
        public string Seat_Name { get; set; }
    }
}
