//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowTimingsDetailsInfo
    {
        public ShowTimingsDetailsInfo()
        {
            this.Bookings = new HashSet<Booking>();
            this.MovieTheatres = new HashSet<MovieTheatre>();
        }
    
        public int STDI_id { get; set; }
        public string ShowTimeSlots_Screens { get; set; }
        public int ShowTickets { get; set; }
        public int ShowBookedTickets { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<MovieTheatre> MovieTheatres { get; set; }
    }
}
