//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTheatre
    {
        public SubTheatre()
        {
            this.Bookings = new HashSet<Booking>();
            this.MovieTheatres = new HashSet<MovieTheatre>();
        }
    
        public int SubTh_id { get; set; }
        public string SubTh_Name { get; set; }
        public string SubTh_location { get; set; }
        public int TheatreCompanyBelongsTo { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<MovieTheatre> MovieTheatres { get; set; }
        public virtual TheatreCompany TheatreCompany { get; set; }
    }
}
