//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheatreCompany
    {
        public TheatreCompany()
        {
            this.SubTheatres = new HashSet<SubTheatre>();
        }
    
        public int Theater_id { get; set; }
        public string Th_name { get; set; }
    
        public virtual ICollection<SubTheatre> SubTheatres { get; set; }
    }
}
